[package]
name = "agilent_pad"
version = "0.1.0"
authors = ["cyrozap"]
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
nom = "7.1.3"

[dev-dependencies]
clap = { version = "4.1.4", features = ["derive"] }
